DELIMITER $$

DROP VIEW IF EXISTS `ecom`.`credit_sale`$$

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `credit_sale` AS select (select `product`.`PRODUCT_NAME` AS `product_name` from `product` where (`invoice_detail`.`PRODUCT_ASSOCIATION_ID` = `product`.`PRODUCT_ID`)) AS `product`,(select `outlet`.`OUTLET_NAME` AS `outlet_name` from `outlet` where (`invoice_main`.`OUTLET_ASSOCICATION_ID` = `outlet`.`OUTLET_ID`)) AS `outlet`,cast(`invoice_main`.`CREATED_DATE` as date) AS `created_date`,sum(((`invoice_detail`.`ITEM_SALE_PRICE` * `invoice_detail`.`PRODUCT_QUANTITY`) - (coalesce(`invoice_main`.`INVOICE_DISCOUNT_AMT`,0) / (select count(`invoice_detail`.`INVOICE_MAIN_ASSOCICATION_ID`) AS `count(``invoice_detail``.``invoice_main_assocication_id``)` from `invoice_detail` where (`invoice_detail`.`INVOICE_MAIN_ASSOCICATION_ID` = `invoice_main`.`INVOICE_MAIN_ID`))))) AS `revenue`,(sum(((`invoice_detail`.`ITEM_SALE_PRICE` * `invoice_detail`.`PRODUCT_QUANTITY`) - (coalesce(`invoice_main`.`INVOICE_DISCOUNT_AMT`,0) / (select count(`invoice_detail`.`INVOICE_MAIN_ASSOCICATION_ID`) AS `count(``invoice_detail``.``invoice_main_assocication_id``)` from `invoice_detail` where (`invoice_detail`.`INVOICE_MAIN_ASSOCICATION_ID` = `invoice_main`.`INVOICE_MAIN_ID`))))) + sum((`invoice_detail`.`ITEM_TAX_AMOUNT` * `invoice_detail`.`PRODUCT_QUANTITY`))) AS `revenue_tax_incl`,sum((`invoice_detail`.`ITEM_ORIGNAL_AMT` * `invoice_detail`.`PRODUCT_QUANTITY`)) AS `cost_of_goods`,(sum((`invoice_detail`.`ITEM_SALE_PRICE` * `invoice_detail`.`PRODUCT_QUANTITY`)) - sum((`invoice_detail`.`ITEM_ORIGNAL_AMT` * `invoice_detail`.`PRODUCT_QUANTITY`))) AS `gross_profit`,coalesce((100 - ((sum(`invoice_detail`.`ITEM_ORIGNAL_AMT`) / sum(`invoice_detail`.`ITEM_SALE_PRICE`)) * 100)),0) AS `margin`,sum(CASE  
            WHEN `invoice_detail`.`ITEM_SALE_PRICE` < 0 THEN `invoice_detail`.`product_quantity` * -1
		ELSE `invoice_detail`.`product_quantity`
        END) AS `items_sold`,sum(`invoice_detail`.`ITEM_TAX_AMOUNT`) AS `tax`,`invoice_main`.`COMPANY_ASSOCIATION_ID` AS `company_association_id`,`invoice_main`.`OUTLET_ASSOCICATION_ID` AS `outlet_assocication_id`,`receipt`.`PAYMENT_TYPE_ASSOCICATION_ID` AS `PAYMENT_TYPE_ASSOCICATION_ID` from ((`invoice_detail` join `invoice_main` on((`invoice_main`.`INVOICE_MAIN_ID` = `invoice_detail`.`INVOICE_MAIN_ASSOCICATION_ID`))) join `receipt` on(((`receipt`.`INVOICE_MAIN_ASSOCICATION_ID` = `invoice_main`.`INVOICE_MAIN_ID`) and (`receipt`.`PAYMENT_TYPE_ASSOCICATION_ID` = 2)))) where (`invoice_main`.`STATUS_ASSOCICATION_ID` <> 11) group by `invoice_detail`.`PRODUCT_ASSOCIATION_ID`,cast(`invoice_main`.`CREATED_DATE` as date) order by cast(`invoice_main`.`CREATED_DATE` as date)$$

DELIMITER ;