use ecom;

DELIMITER $$

DROP VIEW IF EXISTS `ecom`.`stock_order_v`$$

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `stock_order_v` AS 
select `s`.`STOCK_ORDER_ID` AS `STOCK_ORDER_ID`, COALESCE(`s`.`STOCK_REF_NO`, '') AS `STOCK_REF_NO`,COALESCE(`s`.`STATUS_ASSOCICATION_ID`, 0) AS `STATUS_ASSOCICATION_ID`,
COALESCE(`s`.`DILIVERY_DUE_DATE`, CURRENT_TIMESTAMP) AS `DILIVERY_DUE_DATE`, COALESCE(`s`.`CONTACT_ID`, 0) AS `CONTACT_ID`, COALESCE(`s`.`ORDER_NO`, '') AS `ORDER_NO`,
COALESCE(`s`.`OUTLET_ASSOCICATION_ID`, 0) AS `OUTLET_ASSOCICATION_ID`, 
COALESCE(`s`.`SOURCE_OUTLET_ASSOCICATION_ID`, 0) AS `SOURCE_OUTLET_ASSOCICATION_ID`,
COALESCE(`s`.`CONTACT_INVOICE_NO`, '') AS `CONTACT_INVOICE_NO`, COALESCE(`s`.`STOCK_ORDER_DATE`, CURRENT_TIMESTAMP) AS `STOCK_ORDER_DATE`, COALESCE(`s`.`REMARKS`, '') AS `REMARKS`,
COALESCE(`s`.`ORDR_RECV_DATE`, CURRENT_TIMESTAMP) AS `ORDR_RECV_DATE`, COALESCE(`s`.`RETURN_NO`, '') AS `RETURN_NO`, COALESCE(`s`.`STOCK_ORDER_TYPE_ASSOCICATION_ID`, 0) AS `STOCK_ORDER_TYPE_ASSOCICATION_ID`,
COALESCE(`s`.`AUTOFILL_REORDER`, 0) AS `AUTOFILL_REORDER`, COALESCE(`s`.`RETAIL_PRICE_BILL`, 0) AS `RETAIL_PRICE_BILL`, COALESCE(`s`.`ACTIVE_INDICATOR`, 0) AS `ACTIVE_INDICATOR`,
COALESCE(`s`.`CREATED_DATE`, CURRENT_TIMESTAMP) AS `CREATED_DATE`, COALESCE(`s`.`LAST_UPDATED`, CURRENT_TIMESTAMP) AS `LAST_UPDATED`, COALESCE(`s`.`CREATED_BY`, 0) AS `CREATED_BY`, COALESCE(`s`.`UPDATED_BY`, 0) AS `UPDATED_BY`,
COALESCE(`s`.`COMPANY_ASSOCIATION_ID`, 0) AS `COMPANY_ASSOCIATION_ID`, COALESCE(`s`.`TOTAL_ITEMS`, 0) AS `TOTAL_ITEMS`, COALESCE(`s`.`TOTAL_AMOUNT`, 0) AS `TOTAL_AMOUNT`,
COALESCE(`st`.`STATUS_DESC`, '') AS `STATUS_DESC`, COALESCE(`stype`.`STOCK_ORDER_TYPE_DESC`, '') AS `STOCK_ORDER_TYPE_DESC`, COALESCE(`o1`.`OUTLET_NAME`, '') AS `outlet`,
COALESCE(`o2`.`OUTLET_NAME`, '') AS `source`, COALESCE(`c`.`CONTACT_NAME`, '') AS `Supplier` from (((((`stock_order` `s` left join `outlet` `o1` on((`o1`.`OUTLET_ID` = `s`.`OUTLET_ASSOCICATION_ID`))) 
left join `outlet` `o2` on((`o2`.`OUTLET_ID` = `s`.`SOURCE_OUTLET_ASSOCICATION_ID`)))
 left join `contact` `c` on((`c`.`CONTACT_ID` = `s`.`CONTACT_ID`))) 
left join `status` `st` on((`st`.`STATUS_ID` = `s`.`STATUS_ASSOCICATION_ID`))) 
left join `stock_order_type` `stype` on((`stype`.`STOCK_ORDER_TYPE_ID` = `s`.`STOCK_ORDER_TYPE_ASSOCICATION_ID`))) 
order by `s`.`STOCK_ORDER_ID` desc$$
DELIMITER ;
