use ecom;

UPDATE product prod 
   JOIN (SELECT GROUP_CONCAT(distinct (VARIANT_ATTRIBUTE_VALUE_1)) as attr1,PRODUCT_ASSOCICATION_ID   FROM product_variant where  ACTIVE_INDICATOR = true group by PRODUCT_ASSOCICATION_ID) VAR1 ON VAR1.PRODUCT_ASSOCICATION_ID = prod.PRODUCT_ID  
   SET prod.attribute1 = VAR1.attr1;

UPDATE product prod 
   JOIN (SELECT GROUP_CONCAT(distinct (VARIANT_ATTRIBUTE_VALUE_2)) as attr2,PRODUCT_ASSOCICATION_ID   FROM product_variant where  ACTIVE_INDICATOR = true group by PRODUCT_ASSOCICATION_ID) VAR2 ON VAR2.PRODUCT_ASSOCICATION_ID = prod.PRODUCT_ID  
   SET prod.attribute2 = VAR2.attr2;

UPDATE product prod 
   JOIN (SELECT GROUP_CONCAT(distinct (VARIANT_ATTRIBUTE_VALUE_3)) as attr3,PRODUCT_ASSOCICATION_ID   FROM product_variant where  ACTIVE_INDICATOR = true group by PRODUCT_ASSOCICATION_ID) VAR3 ON VAR3.PRODUCT_ASSOCICATION_ID = prod.PRODUCT_ID  
   SET prod.attribute3 = VAR3.attr3;